name: Deploying

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TIPXMR_SERVER_HOST }}
          username: ${{ secrets.TIPXMR_SERVER_USER }}
          key: ${{ secrets.SSH_KEY_TIPXMR_SERVER }}
          port: ${{ secrets.TIPXMR_SERVER_SSH_PORT }}
          script: |
            cd ~/dev.tipxmr.live/tipxmr-backend
            pm2 kill
            rm -rf node_modules package-lock.json
            git pull
            npm install 
            npm run build
            pm2 start ecosystem.json --env develop
