name: Node.js CI

on:
  push:
    branches: [ develop, feature/138-continious_deployment ]
  pull_request:
    branches: [ develop, feature/138-continious_deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
          CI: false
    - name: Deploy to dev.tipxmr.live
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_TIPXMR_SERVER }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.TIPXMR_SERVER_HOST }}
        REMOTE_USER: ${{ secrets.TIPXMR_SERVER_USER }}
        REMOTE_PORT: ${{ secrets.TIPXMR_SERVER_SSH_PORT }}
        TARGET: ${{ secrets.REMOTE_TARGET_PATH_DEVELOP }}
