name: Node.js CI

on:
  push:
    branches: [old]
  pull_request:
    branches: [old]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: false
      - name: Deploy to dev.tipxmr.live
        uses: easingthemes/ssh-deploy@v2.1.6
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_TIPXMR_SERVER }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          EXCLUDE: "/node_modules/"
          REMOTE_HOST: ${{ secrets.TIPXMR_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.TIPXMR_SERVER_USER }}
          REMOTE_PORT: ${{ secrets.TIPXMR_SERVER_SSH_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET_PATH_DEVELOP }}
